name: Generate 6-bit DAC Table

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1) Checkout code
      uses: actions/checkout@v3

    - name: 2) List workspace for debugging
      run: |
        echo "Working directory: $(pwd)"
        echo "Contents:"
        ls -R .

    - name: 3) Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 4) Install reqs (if any)
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: 5) Run table generator
      run: |
        echo "Running generate_dac_table.py"
        python3 generate_dac_table.py
        echo "Exit code: $?"

    - name: 6) List workspace AFTER script
      run: |
        echo "After generation, contents:"
        ls -R .

    - name: 7) Commit DAC6bit_Table.md (if changed)
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update DAC6bit_Table.md"
        file_pattern: "DAC6bit_Table.md"
